# Generated by Django 5.1 on 2024-10-01 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tip_plant_is_plant_of_month'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garden',
            name='description',
        ),
        migrations.RemoveField(
            model_name='gardenplant',
            name='notes',
        ),
        migrations.AddField(
            model_name='gardenplant',
            name='last_pruned',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gardenplant',
            name='last_watered',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='garden',
            name='name',
            field=models.CharField(default='My Garden', max_length=100),
        ),
        migrations.AlterField(
            model_name='garden',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='garden', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gardenplant',
            name='garden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='core.garden'),
        ),
    ]
