# Generated by Django 5.1 on 2024-10-09 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_garden_description_remove_gardenplant_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gardenplant',
            name='last_fertilized',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gardenplant',
            name='location_in_garden',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gardenplant',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='fertilizing_frequency',
            field=models.IntegerField(blank=True, help_text='Number of days between fertilizing', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='humidity_preference',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='plant',
            name='ideal_temperature_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='ideal_temperature_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='sunlight_needs',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='plant',
            name='watering_frequency',
            field=models.IntegerField(blank=True, help_text='Number of days between watering', null=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlantCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_type', models.CharField(choices=[('WATER', 'Watering'), ('PRUNE', 'Pruning'), ('FERTILIZE', 'Fertilizing')], max_length=10)),
                ('last_performed', models.DateTimeField(blank=True, null=True)),
                ('next_due', models.DateTimeField()),
                ('is_done', models.BooleanField(default=False)),
                ('garden_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_tasks', to='core.gardenplant')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('precipitation', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='core.garden')),
            ],
            options={
                'unique_together': {('garden', 'date')},
            },
        ),
    ]
