# Generated by Django 5.1 on 2024-10-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_gardenplant_location_in_garden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced')], default=1),
        ),
    ]
