# Generated by Django 5.1 on 2024-10-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_plant_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='plant_of_month_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
