# Generated by Django 5.1 on 2024-10-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_plant_plant_of_month_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='best_planting_season',
            field=models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter')], default='spring', max_length=20),
            preserve_default=False,
        ),
    ]
