# Generated by Django 5.1 on 2024-10-13 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_plant_best_planting_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='ideal_temperature_max',
            field=models.FloatField(blank=True, help_text='Maximum ideal temperature in Celsius', null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='ideal_temperature_min',
            field=models.FloatField(blank=True, help_text='Minimum ideal temperature in Celsius', null=True),
        ),
    ]
