# Generated by Django 5.1 on 2024-10-14 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumpost',
            name='updated_at',
        ),
    ]
